"use client";

import { useLanguage, pick } from "@/lib/i18n";
import { Card, CardContent } from "@/components/ui/card";

const copy = {
  en: {
    title: "What's real vs. what's mocked",
    intro:
      "SpashtPF is a hackathon prototype. Some of it reflects real, publicly documented EPFO process — some of it is deliberately simulated so no live government system is ever touched. Here's exactly which is which.",
    researchNote:
      "Rejection categories and portal flow are based on publicly available EPFO guidance and reported citizen experiences, not access to any EPFO system.",
    realTitle: "What's real",
    real: [
      "The 7 rejection categories (name mismatch, DOB mismatch, exit-date gap, EPS gap, employer attestation, bank KYC failure, ineligible claim type)",
      "Portal terminology and claim statuses (Submitted, Under Process, Settled, Rejected)",
      "Eligibility rules — e.g. Form 19 can only be filed 2 months after leaving, and the EPFiGMS grievance flow structure",
      "Form names and the real EPFiGMS grievance categories (Withdrawal/Settlement, KYC/Bank Account, Pension Payment, Transfer of PF)",
      "The fuzzy name-matching logic — a one-character name difference really does trigger automated rejection",
    ],
    mockedTitle: "What's mocked",
    mocked: [
      "The EPFO member database itself — every claim, UAN, and name here is synthetic",
      "OTP delivery — the demo OTP is fixed and never sent anywhere",
      "Actual fund transfer — no money moves, ever",
      "Actual grievance submission — the escalate screen drafts text for you to file yourself on the real epfigms.gov.in; SpashtPF never submits on your behalf",
      "The plain-language decode itself is currently generated by rule-based templates (not a live AI model call) — it's written so a real OpenAI model call can be swapped in behind the same function without changing any screen",
    ],
    otherChannelsTitle: "Real channels this prototype doesn't build",
    otherChannels: [
      "SMS status/balance check: send \"EPFOHO UAN <LangCode>\" to 7738299899",
      "UMANG mobile app, which also includes EPFiGMS access",
      "Missed-call balance service",
      "Form 10C — for pension (EPS) withdrawal when service is under 10 years — is a separate claim type, out of scope here",
    ],
    scopeNote:
      "Scope is deliberately narrow: Form 19 (full & final PF settlement) only. No other claim type is built.",
  },
  hi: {
    title: "क्या असली है, क्या काल्पनिक",
    intro:
      "SpashtPF एक हैकाथॉन प्रोटोटाइप है। इसका कुछ हिस्सा असली, सार्वजनिक रूप से दस्तावेज़ीकृत EPFO प्रक्रिया दर्शाता है — कुछ हिस्सा जानबूझकर काल्पनिक है ताकि किसी असली सरकारी सिस्टम को छुआ न जाए। यहाँ बिल्कुल स्पष्ट है कि क्या क्या है।",
    researchNote:
      "अस्वीकृति श्रेणियाँ और पोर्टल प्रवाह सार्वजनिक रूप से उपलब्ध EPFO मार्गदर्शन और नागरिकों के अनुभवों पर आधारित हैं, किसी EPFO सिस्टम तक पहुँच पर नहीं।",
    realTitle: "क्या असली है",
    real: [
      "7 अस्वीकृति श्रेणियाँ (नाम बेमेल, जन्मतिथि बेमेल, सेवा समाप्ति तिथि में कमी, EPS कमी, नियोक्ता सत्यापन, बैंक KYC विफलता, अपात्र दावा प्रकार)",
      "पोर्टल की शब्दावली और दावा स्थितियाँ (प्रस्तुत, प्रक्रिया में, निपटाया गया, अस्वीकृत)",
      "पात्रता नियम — जैसे फॉर्म 19 नौकरी छोड़ने के 2 महीने बाद ही दाखिल हो सकता है, और EPFiGMS शिकायत प्रवाह की संरचना",
      "फॉर्म नाम और असली EPFiGMS शिकायत श्रेणियाँ (निकासी/निपटान, KYC/बैंक खाता, पेंशन भुगतान, PF स्थानांतरण)",
      "फ़ज़ी नाम-मिलान तर्क — एक अक्षर का अंतर वाकई स्वचालित अस्वीकृति ट्रिगर करता है",
    ],
    mockedTitle: "क्या काल्पनिक है",
    mocked: [
      "EPFO सदस्य डेटाबेस स्वयं — यहाँ हर दावा, UAN और नाम काल्पनिक है",
      "OTP डिलीवरी — डेमो OTP स्थिर है और कहीं नहीं भेजा जाता",
      "वास्तविक धनराशि हस्तांतरण — कभी कोई पैसा नहीं चलता",
      "वास्तविक शिकायत प्रस्तुतीकरण — escalate स्क्रीन आपके लिए पाठ तैयार करती है ताकि आप इसे असली epfigms.gov.in पर स्वयं दर्ज करें; SpashtPF आपकी ओर से कभी जमा नहीं करता",
      "सरल-भाषा व्याख्या अभी नियम-आधारित टेम्पलेट से तैयार होती है (लाइव AI मॉडल कॉल नहीं) — इसे इस तरह लिखा गया है कि असली OpenAI मॉडल कॉल उसी फ़ंक्शन के पीछे बिना किसी स्क्रीन को बदले जोड़ी जा सके",
    ],
    otherChannelsTitle: "असली चैनल जो इस प्रोटोटाइप में नहीं बनाए गए",
    otherChannels: [
      "SMS स्थिति/बैलेंस जांच: \"EPFOHO UAN <LangCode>\" 7738299899 पर भेजें",
      "UMANG मोबाइल ऐप, जिसमें EPFiGMS पहुँच भी शामिल है",
      "मिस्ड-कॉल बैलेंस सेवा",
      "फॉर्म 10C — 10 वर्ष से कम सेवा पर पेंशन (EPS) निकासी के लिए — एक अलग दावा प्रकार है, यहाँ शामिल नहीं",
    ],
    scopeNote:
      "दायरा जानबूझकर सीमित रखा गया है: केवल फॉर्म 19 (पूर्ण एवं अंतिम PF निपटान)। कोई अन्य दावा प्रकार नहीं बनाया गया।",
  },
};

export default function TransparencyPage() {
  const { lang } = useLanguage();
  const t = pick(lang, copy);

  return (
    <div className="mx-auto max-w-3xl px-4 py-10 sm:px-6">
      <h1 className="text-2xl font-bold text-foreground">{t.title}</h1>
      <p className="mt-2 text-sm leading-relaxed text-muted">{t.intro}</p>

      <div className="mt-6 grid gap-4 sm:grid-cols-2">
        <Card>
          <CardContent className="pt-5">
            <h2 className="mb-3 font-semibold text-success">{t.realTitle}</h2>
            <ul className="flex flex-col gap-2">
              {t.real.map((item) => (
                <li key={item} className="text-sm leading-relaxed text-foreground">
                  {item}
                </li>
              ))}
            </ul>
          </CardContent>
        </Card>

        <Card>
          <CardContent className="pt-5">
            <h2 className="mb-3 font-semibold text-warning">{t.mockedTitle}</h2>
            <ul className="flex flex-col gap-2">
              {t.mocked.map((item) => (
                <li key={item} className="text-sm leading-relaxed text-foreground">
                  {item}
                </li>
              ))}
            </ul>
          </CardContent>
        </Card>
      </div>

      <p className="mt-6 rounded-md border border-border bg-muted-tint px-4 py-3 text-sm text-muted">
        {t.researchNote}
      </p>

      <div className="mt-8">
        <h2 className="mb-2 font-semibold text-foreground">{t.otherChannelsTitle}</h2>
        <ul className="flex flex-col gap-1.5">
          {t.otherChannels.map((item) => (
            <li key={item} className="text-sm leading-relaxed text-muted">
              • {item}
            </li>
          ))}
        </ul>
        <p className="mt-3 text-sm font-medium text-foreground">{t.scopeNote}</p>
      </div>
    </div>
  );
}
